In [1]:
# Importem les llibreries necessàries
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Importem els arxius .csv amb els datasets que utilitzarem
equipos = pd.read_csv('stats_equipos.csv', encoding='latin-1')
jugadores = pd.read_csv('stats_jugadores.csv', encoding='latin-1')

In [4]:
# Definim el dataframe 'stats_equipos' i 'stats_jugadores'
stats_equipos = pd.DataFrame(equipos)
stats_jugadores = pd.DataFrame(jugadores)

In [6]:
# Mostrem les columnes que té el dataframe que hem definit prèviament 'stats_equipos'
stats_equipos.columns

Index(['Unnamed: 0', 'Teams', 'MP', 'W', 'D', 'L', 'GF', 'GA', '+/-', 'Pts',
       'Group'],
      dtype='object')

In [7]:
# Esborrem les columnes innecessàries
del stats_equipos['Unnamed: 0']

In [8]:
# Modifiquem el nom de totes les columnes
stats_equipos = stats_equipos.rename(columns={"Teams":"Equipos"})
stats_equipos = stats_equipos.rename(columns={"MP":"Partidos Jugados"})
stats_equipos = stats_equipos.rename(columns={"W":"Victorias"})
stats_equipos = stats_equipos.rename(columns={"D":"Empates"})
stats_equipos = stats_equipos.rename(columns={"L":"Derrotas"})
stats_equipos = stats_equipos.rename(columns={"GF":"Goles a favor"})
stats_equipos = stats_equipos.rename(columns={"GA":"Goles en contra"})
stats_equipos = stats_equipos.rename(columns={"+/-":"Diferencia de goles"})
stats_equipos = stats_equipos.rename(columns={"Pts":"Puntos"})
stats_equipos = stats_equipos.rename(columns={"Group":"Grupo"})

In [9]:
# Mostrem com ha quedat el dataframe
stats_equipos.head(32)

,Equipos,Partidos Jugados,Victorias,Empates,Derrotas,Goles a favor,Goles en contra,Diferencia de goles,Puntos,Grupo
0,Netherlands (Q),3,2,1,0,5,1,4,7,A
1,Senegal (Q),3,2,0,1,4,3,1,6,A
2,Ecuador,3,1,1,1,4,3,1,4,A
3,Qatar,3,0,0,3,1,7,-6,0,A
4,England (Q),3,2,1,0,9,2,7,7,B
5,USA (Q),3,1,2,0,2,1,1,5,B
6,Iran,3,1,0,2,4,7,-3,3,B
7,Wales,3,0,1,2,1,6,-5,1,B
8,Argentina (Q),3,2,0,1,5,2,3,6,C
9,Poland (Q),3,1,1,1,2,2,0,4,C
10,Mexico,3,1,1,1,2,3,-1,4,C
11,Saudi Arabia,3,0,1,2,3,4,-1,3,C
12,France (Q),3,2,0,1,6,3,3,6,D
13,Australia (Q),3,2,0,1,6,4,-2,3,D
14,Tunisia,3,1,1,1,1,1,0,1,D
15,Denmark,3,0,1,2,1,3,-2,1,D
16,Japan (Q),3,2,0,1,4,3,1,6,E
17,Spain (Q),3,1,1,1,9,3,6,4,E
18,Germany,3,1,1,1,6,5,1,4,E
19,Costa Rica,3,1,0,2,3,11,-8,3,E
20,Morocco (Q),3,3,1,0,4,1,3,7,F
21,Croatia (Q),3,1,2,0,4,1,3,5,F
22,Belgium,3,1,1,1,1,1,0,4,F
23,Canada,3,0,0,3,2,7,-5,0,F
24,Brazil (Q),3,2,0,1,3,1,2,6,G
25,Switzerland (Q),3,2,0,1,4,3,1,6,G
26,Cameroon,3,1,1,1,4,4,0,4,G
27,Serbia,3,0,1,2,5,8,-3,1,G
28,Portugal (Q),3,2,0,1,6,4,2,6,H
29,South Korea (Q),3,1,1,1,4,4,0,4,H
30,Uruguay,3,1,1,1,2,2,0,4,H
31,Ghana,3,1,0,2,5,7,-2,3,H

In [10]:
# Mostrem les columnes que té el dataframe que hem definit prèviament 'stats_jugadores'
stats_jugadores.columns

Index(['Nationality ', 'FIFA Ranking ', 'National Team Kit Sponsor',
       'Position', 'National Team Jersey Number', 'Player DOB', 'Club ',
       'Player Name ', ' Appearances', 'Goals Scored ', 'Assists Provided ',
       'Dribbles per 90', 'Interceptions per 90', 'Tackles per 90',
       'Total Duels Won per 90', 'Save Percentage', 'Clean Sheets',
       'Brand Sponsor/Brand Used'],
      dtype='object')

In [11]:
# Esborrem les columnes innecesàries
del stats_jugadores['FIFA Ranking ']
del stats_jugadores['National Team Kit Sponsor']
del stats_jugadores['National Team Jersey Number']
del stats_jugadores['Player DOB']
del stats_jugadores['Club ']
del stats_jugadores[' Appearances']
del stats_jugadores['Assists Provided ']
del stats_jugadores['Dribbles per 90']
del stats_jugadores['Interceptions per 90']
del stats_jugadores['Tackles per 90']
del stats_jugadores['Total Duels Won per 90']
del stats_jugadores['Save Percentage']
del stats_jugadores['Clean Sheets']
del stats_jugadores['Brand Sponsor/Brand Used']

In [12]:
# Modifiquem el nom de les totes columnes
stats_jugadores = stats_jugadores.rename(columns={"Nationality":"Equipos"})
stats_jugadores = stats_jugadores.rename(columns={"Position":"Posiciones"})
stats_jugadores = stats_jugadores.rename(columns={"Player Name":"Jugadores"})
stats_jugadores = stats_jugadores.rename(columns={"Goals Scored":"Goles Marcados"})

In [13]:
# Mostrem com ha quedat el dataframe
stats_jugadores.head(100)

   Nationality  Posiciones       Player Name  Goals Scored
0     Argentina         GK  Emiliano Martinez             0
1     Argentina         GK      Franco Armani             -
2     Argentina         GK     Geronimo Rulli             -
3     Argentina         DF   Nicolas Otamendi             0
4     Argentina         DF       Marcos Acuna             0
..          ...        ...                ...           ...
95     Morocco          FW     Sofiane Boufal             0
96     Morocco          FW  Zakaria Aboukhlal             1
97     Morocco          FW      Anass Zaroury             0
98     Morocco          FW    Abde Ezzalzouli             0
99     Morocco          FW        Ilias Chair             0

[100 rows x 4 columns]